codecov:
  notify:
    require_ci_to_pass: yes
  max_report_age: off
  bot: "codecov-bot"

comment:
  layout: "header, diff, flags"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

flags:
  unit:
    paths: #note, accepts globs, not regexes
      - "*_test.go"
    carryforward: true