on: ["push", "pull_request", "workflow_dispatch"]

name: Quality
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go mod download
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}